Implement All Remaining Features the Original SAM Does
PaulCombal/SamRewritten-legacy pull request #61
Opened 2020-05-19 07:16 UTC by wgpierce

Implement only showing locked/unlocked achievements.
Implement launching app in separate window.

This is branched off feat-timed-modifications so I could continue working. It'll apply cleanly on dev after feat-timed-modifications is merged to dev.

2020-05-19 16:00 UTC, PaulCombal commented on src/types/Achievement.h
> +    uint64_t num;
Can you comment above what this is about?

2020-05-19 16:02 UTC, PaulCombal requested changes
Can you give an example usage for CLI timed achievement unlocking under the options list on the README?

Also if you want to show it off, you can write a little paragraph about timed achievements ;)

2020-05-19 16:16 UTC, PaulCombal commented
Really awesome work! I can't believe you put so much effort in that, congrats! There's just the tw little things I pointed out in the review, but also about the new "timed" window, can you add a little bit of padding on the edges of the window? 5-10px let's say. 
Also, it looks like there would be conflicts when merging, I think this also needs to be sorted out, maybe by merging dev into the feature branch first?
Other than that, fantastic! Tell me what you think

2020-05-20 05:17 UTC, wgpierce commented on src/types/Achievement.h
> +    uint64_t num;
Done.

2020-05-20 05:20 UTC, wgpierce commented
> Can you give an example usage for CLI timed achievement unlocking under the options list on the README?

Done.

> Also if you want to show it off, you can write a little paragraph about timed achievements ;)

Done. Added a "features" section too for significant features.

> about the new "timed" window, can you add a little bit of padding on the edges of the window? 5-10px let's say.

Done.

> Also, it looks like there would be conflicts when merging, I think this also needs to be sorted out, maybe by merging dev into the feature branch first?

Resolved.

Any other changes you want to make to the README? Do you want to bump the screenshots? I can if you want (though I use a dark theme).

2020-05-20 12:33 UTC, PaulCombal approved these changes

2020-05-21 05:09 UTC, merged